"""add_weapon_id_to_characters2

Revision ID: 05c83471321f
Revises: 6e3e793715a9
Create Date: 2025-02-27 10:03:09.008643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c83471321f'
down_revision: Union[str, None] = '6e3e793715a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'weapons', ['weapon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'users', ['name'], ['username'])
    # ### end Alembic commands ###
