"""add_level_to_characters

Revision ID: 4ec016f5426b
Revises: 05c83471321f
Create Date: 2025-02-27 11:16:29.763737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec016f5426b'
down_revision: Union[str, None] = '05c83471321f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'weapons', ['weapon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'users', ['name'], ['username'])
    op.drop_column('characters', 'level')
    # ### end Alembic commands ###
