"""add status column to characters table

Revision ID: 9e5ec58be09f
Revises: 87cbb70af72c
Create Date: 2025-02-26 17:07:57.280191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5ec58be09f'
down_revision: Union[str, None] = '87cbb70af72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'characters', 'users', ['name'], ['username'])
    # ### end Alembic commands ###
